### ISSUE TITLE
Minimum crop area size

### ISSUE THREAD

**Issue by lukehutch** [iazel/image_crop#1]
Thanks for opening the issue tracker!

I want to be able to restrict the crop area to a given minimum pixel dimension. Obviously if this size doesn't fit within the image, the smallest rectangle of the same aspect ratio that fits within the image should be the minimum size instead.

I haven't looked closely enough yet to see if this is easy to implement, but I'm wondering if the `target: TargetSize` parameter provided to the crop controller could be interpreted as the minimum crop size, if a minimum crop size constraint is requested? I think this would make sense, since as it stands, I believe this `TargetSize` is only used to determine the aspect ratio of the crop window.

Let me know if you have any ideas about this, before I jump in and start trying to modify the code...

**Comment by iazel** [comment]
`TargetSize` isn't limited to the aspect ratio, but, as the name suggests, it's the final size of the image (properly scaled according to device pixel ratio). Thus, if you set `TargetSize` to 300x400 and your device pixel ratio is 2.0, then the final image will always be 600x400 raw pixels, no matter how small or big is the crop area.

The dimension of the crop area is only needed to cut the right section of the image :)

That's said, what would be the use of a configurable "minimum" crop area? :thinking: 

EDIT: I just realized that I haven't released the pixel ratio part yet :D Let me fix it!

**Comment by lukehutch** [comment]
I see -- I don't think you should incorporate the device pixel ratio though. I want to crop images so that the final image is 1080x1920, regardless of the device pixel ratio -- unless the cropping area is smaller than 1080x1920, in which case the image should not be scaled up, but should still match the 16:9 aspect ratio.

I thought `TargetSize` was used to set the aspect ratio, because (as far as I remember) that's the thing I changed when I wanted the aspect ratio of the cropping area to change...

**Comment by iazel** [comment]
> unless the cropping area is smaller than 1080x1920, in which case the image should not be scaled up, but should still match the 16:9 aspect ratio

I'm not sure if I've understood what you meant here. When you say "crop area", do you mean the part that the user can actually resize? Like, you want to have the crop area to start at 1080x1920, supposing the user will most often pass an image that is larger than that. Resizing the crop area will then change the final image dimensions once cropped. Is that what you meant?

**Comment by lukehutch** [comment]
The crop area is currently constrained to have the same aspect ratio as `TargetArea`, which is reasonable as things stand.

However, I think there is a better way to do this, through these parameters:
* `aspectRatio`, which specifies the aspect ratio of the crop region. If not specified, the aspect ratio is unconstrained.
* `scaledPixelsInLongerDimension`, which specifies the size to scale down the longer dimension of the crop region to (in image pixels, not device pixels). The crop region is never scaled up to this size, only scaled down. This does not constrain the maximum size of the crop region (the whole image is the maximum size of the crop region, or at least the longest dimension that fits into the image). It only  governs scaling after the raw image is cropped to the specified area. (Cropping very frequently must be followed by scaling.) If this is not specified, then the cropped image is not scaled (the scale factor is set to 1.0).
* `minScaledPixelsInLongerDimension`, which specifies the minimum number of image pixels (not device pixels) that are accepted along the longest edge of the cropped and scaled image. This is used together with `aspectRatio` to constrain the minimum dimensions of the crop area, so the user can't select a subimage that is lower-resolution than some acceptable limit. If it is not specified, the user can select an arbitrarily small rectangle.

**Comment by iazel** [comment]
Ok, so you would expect that changing the crop area will also change the final image dimensions, more or less like Gimp and Photoshop works.

Could you please tell me what's your use case? On which platform do you want to use this library?

I'm asking because for my use case (avatar and cover generation) I always want to have a specific image size, opportunely scaled by device pixel ratio for best rendering.

**Comment by lukehutch** [comment]
I'm targeting Android and iOS.

This is for a social networking app. I want all user images to be scaled to 1080x1920 after cropping, unless the cropped size is smaller than that (I don't want images to be scaled up, only scaled down). And I want to restrict the cropping area to a minimum size of 1080x1920, so that you can't select a region smaller than 1080x1920 pixels, unless the original image is already smaller than this.

The files are then uploaded to the server by the app. I want to make sure that all images sent to the server have a consistent pixel dimensions, regardless of the device pixel ratio on the uploading device. (This is why I want to use image pixels, not screen pixels (logical pixels?).)

It sounds like we have similar usecases; however, I want the actual pixel dimensions of the cropped image to be 1080x1920, I don't care about screen pixels for this purpose.

What are the differences and similarities between this and your usecase? I don't fully understand your usecase.

**Comment by iazel** [comment]
Let's see if I've understood you know. You want to have images that are at most 1080x1920 raw pixels, but because you don't want to compromise image quality, you are fine if they are smaller as long as the aspect ratio is respected.

My problem is a little different, in the sense that I don't care about upscaling, I always want the image to have a specific logical size; if it doesn't look good it is up to the user to choose a different image for better quality.

Perhaps you already know it, but just to be clear, when you display images on any screen with pixel ratio greater than 1.0 (most mobile screens), those are already scaled based on device pixel ratio, thus if you try to crop the image to 1080x1920 on a device with 2.0 pixel ratio, then it will look best at 580x960 logical pixels, otherwise it will be upscaled and look grainy.

One thing I'd like to clear: the crop area only decides what portion of the image must be saved, it has zero effect on the final image size. As you previously noted, TargetSize is important for aspect ratio and the crop area will respect it. Resizing the crop area is only useful for the user to make the cut more precise.

What this lib is currently missing for your use case is allowing the image to be cropped to a smaller size than `TargetSize`. An easy workaround may be to simply check the actual image size and set `TargetSize` accordingly, e.g:
```dart
TargetSize calcTargetSize(Image img) {
    const w = 1080;
    const h = 1920;
    final ratio = (img.width < w || img.height < h) ? min(img.width / w, img.height / h) : 1.0; 
    return TargetSize((w * ratio).toInt(), (h * ratio).toInt());
}
```

What do you think?

**Comment by lukehutch** [comment]
I really don't care if the image has to be scaled up to fit the screen, e.g. if I have a JPEG file with image pixel dimensions of 1080x1920, and I'm trying to display it on a screen size of 2160x3840. The eye can't really make out more than 1080p of image resolution on a standard large-sized phone (and anyway, the pixel grid on OLED screens uses the PenTile layout, so the true image resolution isn't really what the spec says).

What I care about is ensuring that the images uploaded to the server have no less than 1080p on the shorter edge after cropping (to preserve image quality), but also that they are not larger than that, to save on server space. In other words, I want to constrain the crop region so that the user can't select a rectangle covering less than 1080 *image* pixels on the shorter dimension, regardless of the screen pixels or device pixel ratio -- and if the user selects a rectangle larger than 1080p, then I want to scale it down to 1080p after cropping.

I can always do the scaling-down as a separate postprocessing step -- that doesn't have to be part of a cropping library. However, I want to be able to limit the minimum size of the crop rectangle, *in image pixels, not logical or device pixels*. Basically I want to calculate a minimum constraint for the crop window size, based on a specified aspect ratio and a specified minimum number of image pixels on the short dimension of the crop region.

Does that make more sense? Thanks for working through this :-)

**Comment by iazel** [comment]
I see, that's different from what I understood before :see_no_evil: 

I don't see any issue with current implementation. As I said before, crop area has no influence on actual image size. If you set `TargetSize(1080, 1920)` you will **always** get an image of that size, no matter how big the original image is or how the user alter the crop area.

By the way, I've pushed the devicePixelRatio code, but it should not impact your use case, just set it to 1 and you're good.

**Comment by lukehutch** [comment]
OK so you are in fact doing scaling then...

I don't want to always get an image of 1080x1920 if I set `TargetSize(1080, 1920)` and the crop area covers only 108x192 pixels!

I only ever want to scale down the crop region to 1080x1920. I don't want to ever scale up or stretch the crop region to the size 1080x1920.

I really want to simply constrain the minimum size of the crop region to `TargetSize`, so that there's no need to scale up.

This is why I suggested having a separate `aspectRatio` field, rather than getting the aspect ratio from `targetSize`. With a fixed aspect ratio, then the minimum crop size can just be specified for one axis, as I indicated in a previous comment.

**Comment by iazel** [comment]
Uhm, I think now I better understand what you are trying to convey. As I see it on the current model, the issue isn't about "minimum crop area", but rather about "maximum scale"!

This is something I haven't considered in such fine details because I'm only interested in generating a small image from a big one. I care about consistent final image size, it's up to the user to take care of image quality. In your case instead it's also important that during cropping the image respects a quality standard. Do you feel like I'm getting closer to your point of view?

> This is why I suggested having a separate aspectRatio field, rather than getting the aspect ratio from targetSize. With a fixed aspect ratio, then the minimum crop size can just be specified for one axis, as I indicated in a previous comment.

What you proposed on your previous post is a fundamental shift on how this lib works. In your model, crop area dictates the cropped image size, akin to how Gimp works, thus it makes sense to talk about a minimum crop area. If that's fine for a desktop app, I feel it offers a more cumbersome UX on a mobile device due to low precision issues.

Complexity will also increase. Right now the crop area is fixed and thus pretty simple, you can only scale it for easier selection, it tells you what pixel to get, but not how big the image will be, hence it is completely disconnected from image quality. To provide a reasonable UX in what you proposed, crop area should move and scale together with the image for more precise handling, but then we also need to have a different mechanism where only the image can be moved and scaled up or down while the crop area stays the same. Then there is also the issue of moving the crop handles out of view and ensuring we properly highlight the crop area while moving it. Plus other corner cases that are often discovered during implementation :)

I can see how that would be the better model for your specific use case, but it's too much code for me to work on. Nonetheless, you are more than welcome to work on it and contribute back ;)

**Comment by lukehutch** [comment]
Yes, now you understand what I have been trying to say! :-D

It's OK, I will give this a shot, I just wanted to run my scenario by you before I dug into the code, to see if there was any common ground we could work on together.

I may just end up working on my own fork, if I can't find a way to do this that doesn't disrupt your own usecase.

Thanks!

**Comment by iazel** [comment]
Wish you happy coding and let me know if you end up publishing it ;)

Please close the issue if you feel like we are done with it 👌

**Comment by lukehutch** [comment]
Sure, I'll make my own tweaks. Thanks!
